/**
 * Writes `COLLECTIONS.md`: every collection this language's evidence rests on, how much text it
 * held, and the URL it came from.
 *
 * The evidence records what each collection saw and how many tokens it held, which is what makes
 * the downloaded text disposable. What it does not record is where the text came from — and a
 * deleted dump with no note of its origin is a claim nobody can re-derive, which is the opposite
 * of the point. So this is the pointer back: run it after a build, commit it, then delete the
 * dumps knowing anybody can fetch them again.
 */
import { writeFileSync } from 'node:fs'
import { dumpUrl, readEvidence } from '@blinkered/attestation'
import * as language from './sources.mjs'

const { LANGUAGE, SOURCES } = language
const evidence = readEvidence('.')

const origin = new Map(SOURCES.map((source) => [source.id, source]))
const rows = [...evidence.totals]
  .sort((left, right) => right[1] - left[1])
  .map(([id, tokens]) => {
    const source = origin.get(id)
    const file = source?.needs?.split('/').pop()
    // Wikimedia names its dumps predictably, so their URL needs no declaring. Everything else
    // says where it came from in `sources.mjs`, because a deleted download whose origin is not
    // written down is a claim nobody can re-derive.
    const url = source?.from ?? (file === undefined ? null : dumpUrl(file))
    const where =
      url !== null && url !== undefined
        ? `[${file}](${url})`
        : id.startsWith('web:')
          ? `fetched from \`${id.slice(4)}\`, recorded in \`searched.tsv\``
          : (file ?? '—')
    return `| \`${id}\` | ${tokens.toLocaleString()} | ${source?.what ?? ''} | ${where} |`
  })

writeFileSync(
  'COLLECTIONS.md',
  `# What this evidence rests on: ${LANGUAGE}

Generated by \`pnpm collections\` from the committed evidence.

Every collection below was read once and its testimony written into \`attestations/\`, along with
the number of playable tokens it held. That total is the denominator of every rate, and recording
it is what makes the downloaded text **disposable**: a later build that adds a family reuses these
lines instead of re-reading gigabytes to rediscover them.

So the dumps are not kept. This table is the pointer back, and a rebuild that wants to re-read a
collection rather than reuse its record only has to put the file back where the path says.

| collection | tokens | what it is | where it came from |
| --- | ---: | --- | --- |
${rows.join('\n')}

Totals are playable tokens after folding, not bytes. A collection missing from this table was
never scanned; one present with no link was fetched by hand and its path is given instead.
`,
)

process.stderr.write(`${LANGUAGE}: wrote COLLECTIONS.md for ${String(rows.length)} collections\n`)
