/**
 * Measures what each family was worth to this language and writes `SATURATION.md`.
 *
 * The method is in `@blinkered/attestation`; the numbers belong here, because they are a fact
 * about this language and nothing else. Reads the committed evidence, so it needs no corpora, no
 * network and no rebuild — the evidence file already records who saw what.
 *
 * Families are added best-first, so the curve shows the shape a careful builder would get rather
 * than the shape this repository's `sources.mjs` happened to produce.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import {
  checkabilityOf,
  conform,
  knee as kneeOf,
  readEvidence,
  saturation,
  sourceFor,
} from '@blinkered/attestation'
import { LANGUAGE } from './sources.mjs'

const evidence = readEvidence('.')
const list = readFileSync('words.txt', 'utf8')
const shipped = list.split('\n').length - 2
const total = evidence.words.length

const familyOf = (source) => {
  try {
    return sourceFor(source).family
  } catch {
    return source
  }
}

const steps = saturation(evidence.words, familyOf, total)

/**
 * How many of this language's families a sceptic could check for themselves.
 *
 * A family whose locators are somebody else's crawl cannot be confirmed from the web — the
 * document holding the word is their corpus file. That is a real difference in how strong a
 * language's evidence is, and it shows up in no coverage number: Russian passes the rule on four
 * families and two of them are crawls.
 */
const checkable = new Set()
const crawled = new Set()
for (const word of evidence.words) {
  for (const attestation of word.attestations) {
    let spec
    try {
      spec = sourceFor(attestation.source)
    } catch {
      continue
    }
    ;(checkabilityOf(spec) === 'crawled' ? crawled : checkable).add(spec.family)
  }
}

// The point of diminishing returns, stated rather than left to the eye. The threshold lives in
// `@blinkered/attestation` so that fifty-one repositories cannot answer one question fifty-one
// different ways, and so the roll-up in that repository draws the same line this one reports.
const knee = kneeOf(steps)

const rows = steps.map((step) => {
  const share = `${(step.share * 100).toFixed(1)}%`
  const gained = step.gained === 0 ? '—' : `+${step.gained.toLocaleString()}`
  return `| ${step.families} | \`${step.added}\` | ${step.kept.toLocaleString()} | ${share} | ${gained} |`
})

writeFileSync(
  'SATURATION.md',
  `# What each family was worth: ${LANGUAGE}

Generated by \`pnpm saturation\` from the committed evidence. The method is in
[blinkered-attestation](../blinkered-attestation); these numbers are a fact about ${LANGUAGE}.

Families are added **best-first**: at each step the one that rescues the most words. So this is
the curve a careful builder would get, not the order this repository happens to list them in.
The first two families keep nothing, which is not padding — it is the shape of a rule that needs
three independent sources.

Candidates: ${total.toLocaleString()}. Shipped: ${shipped.toLocaleString()}.

Of ${String(steps.length)} families, **${String(checkable.size)} can be checked by fetching** —
a stable identifier or a page we fetched ourselves. The other ${String(crawled.size)} are crawls
somebody else made, whose locators record where they found the sentence; the document that holds
it is their published corpus, not the web.

| families | added | kept | coverage | gained |
| --- | --- | --- | --- | --- |
${rows.join('\n')}

${
  knee === undefined
    ? 'No family after the third fell below a twentieth of the best single gain: this language was still being paid for every source it consulted.'
    : `**Diminishing returns from family ${String(knee.families)}** (\`${knee.added}\`, +${knee.gained.toLocaleString()}), where a family first added less than a twentieth of what the best one did.`
}
`,
)

// Whether anybody blessed this list to ship, which is the one thing in this file that is not
// measured. Conforming says the evidence is sound and Blinkered's own floor says the list deals a
// playable board; neither says anybody wants to ship it.
//
// It is carried forward rather than computed, because a build must never be able to bless a
// language or to withdraw one. **Absence means no**: a fresh clone, a deleted file or a brand new
// language starts unblessed and has to be blessed on purpose.
const blessing = existsSync('status.json')
  ? JSON.parse(readFileSync('status.json', 'utf8'))
  : existsSync('ships.json')
    ? JSON.parse(readFileSync('ships.json', 'utf8'))
    : {}

// The same curve as machine-readable data, so the roll-up in `blinkered-attestation` can pull it
// from this repository's main branch rather than re-reading sixty megabytes of evidence. This
// file is the published form of the measurement: small, stable, and everything the chart and the
// roll-up need in one fetch, which is why the blessing lives here too rather than in a second
// file they would have to fetch separately and could disagree with.
writeFileSync(
  'status.json',
  `${JSON.stringify(
    {
      language: LANGUAGE,
      built: evidence.built,
      candidates: total,
      shipped,
      // Three states, not two. `false` used to mean both "we looked and said no" and "nobody has
      // looked yet", and those are different facts: the first is a decision with a reason, the
      // second is work not done. Japanese is held; a language built an hour ago is pending.
      //
      // Anything unrecognised reads as 'pending', because the one thing this must never do is
      // promote a language nobody blessed.
      ships: blessing.ships === true ? true : blessing.ships === false ? false : 'pending',
      decided: blessing.decided ?? null,
      why: blessing.why ?? null,
      // What the shipped list is under. Carried forward like the blessing, for the same reason:
      // a build must not be able to decide a language's terms. Null rather than omitted, because
      // that is what the importer in `blinkered` reads, and it treats null and absent alike —
      // either way it writes no terms and reports the language as undeclared rather than
      // guessing one.
      license: blessing.license ?? null,
      // Whether this repository's list said only what its evidence supported at the moment the
      // curve was measured. It travels with the curve so that a reader of status.json alone —
      // the roll-up, the chart, anyone — never has to take the number on trust.
      conforms: conform(list, evidence).length === 0,
      families: steps.length,
      checkable: checkable.size,
      knee: knee === undefined ? null : knee.families,
      steps: steps.map((step) => ({
        families: step.families,
        added: step.added,
        kept: step.kept,
        share: Number(step.share.toFixed(6)),
        gained: step.gained,
      })),
    },
    null,
    2,
  )}\n`,
)

process.stderr.write(
  `${LANGUAGE}: ${String(steps.length)} families, wrote SATURATION.md and status.json` +
    `${blessing.ships === true ? '' : ' (this language does not ship)'}\n`,
)
for (const step of steps) {
  process.stderr.write(
    `  ${String(step.families).padStart(2)}  ${step.added.padEnd(26)} ` +
      `${String(step.kept).padStart(7)}  ${(step.share * 100).toFixed(1)}%  +${String(step.gained)}\n`,
  )
}
